# ============================================
# Estimate-MSI-Workflow - Main Entry Point
# ============================================


import os

if os.path.exists("config/config.local.yaml"):

    configfile: "config/config.local.yaml"

else:

    configfile: "config/config.yaml"


include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/microsatellites.smk"
include: "rules/reads.smk"
include: "rules/alignment.smk"
include: "rules/variant_calling.smk"
include: "rules/msi.smk"
include: "rules/msisensor.smk"
include: "rules/coverage.smk"
include: "rules/msisensor-pro_scan_plus_varlociraptor.smk"
include: "rules/msisensor-pro_baseline_plus_varlociraptor.smk"
include: "rules/gnomad.smk"


rule all:
    input:
        # Reference genome and index files
        "resources/genome/genome.fasta",
        "resources/genome/genome.gtf",
        "resources/genome/genome.fasta.fai",
        multiext(
            "resources/genome/genome",
            ".amb",
            ".ann",
            ".bwt",
            ".pac",
            ".sa",
        ),
        # FASTQ files for all active samples
        expand(
            "resources/samples/{sample}_{read}.fastq.gz",
            sample=get_active_samples(),
            read=["R1", "R2"],
        ),
        # Alignment files (BAM + index)
        expand(
            "results/mapped/{sample}.bam",
            sample=get_active_samples(),
        ),
        expand(
            "results/mapped/{sample}.bam.bai",
            sample=get_active_samples(),
        ),
        # Variant calls (final BCF)
        expand(
            "results/calls/{sample}.vcf",
            sample=get_active_samples(),
        ),
        # Compressed and indexed VCF
        expand(
            "results/calls/{sample}.vcf.gz",
            sample=get_active_samples(),
        ),
        expand(
            "results/calls/{sample}.vcf.gz.csi",
            sample=get_active_samples(),
        ),
        # Microsatellites (dynamic - only creates needed BEDs)
        get_required_ms_beds(),
        # MSI estimation outputs
        expand(
            [
                "results/msi/{sample}/pseudotime.tsv",
                "results/msi/{sample}/pseudotime.vl.json",
                "results/msi/{sample}/distribution.tsv",
                "results/msi/{sample}/distribution.vl.json",
            ],
            sample=get_active_samples(),
        ),
        # Coverage analysis outputs
        expand(
            [
                "results/coverage/{sample}/ms_coverage.tsv",
                "results/coverage/{sample}/coverage_histogram.html",
            ],
            sample=get_active_samples(),
        ),
        # MSIsensor2 resources
        "resources/msisensor2/models_hg38",
        "resources/msisensor2/microsatellites_msisensor2.list",
        "resources/msisensor2/exons.bed",
        # MSIsensor2 results
        expand(
            [
                "results/msisensor2/{sample}",
                "results/msisensor2/{sample}_dis",
                "results/msisensor2/{sample}_somatic",
            ],
            sample=get_active_samples(),
        ),
        # MSIsensor-pro + Varlociraptor resources
        get_required_ms_beds_msisensor(),
        # MSIsensor-pro + Varlociraptor results
        expand(
            [
                "results/msisensor-pro/msi/{sample}/pseudotime.tsv",
                "results/msisensor-pro/msi/{sample}/pseudotime.vl.json",
                "results/msisensor-pro/msi/{sample}/distribution.tsv",
                "results/msisensor-pro/msi/{sample}/distribution.vl.json",
            ],
            sample=get_active_samples(),
        ),
        # MSIsensor-pro baseline + Varlociraptor resources
        get_required_baseline_beds(),
        # MSIsensor-pro baseline + Varlociraptor results
        expand(
            [
                "results/msisensor-pro-baseline-varlociraptor/msi/{sample}/pseudotime.tsv",
                "results/msisensor-pro-baseline-varlociraptor/msi/{sample}/pseudotime.vl.json",
                "results/msisensor-pro-baseline-varlociraptor/msi/{sample}/distribution.tsv",
                "results/msisensor-pro-baseline-varlociraptor/msi/{sample}/distribution.vl.json",
            ],
            sample=get_active_samples(),
        ),
        # gnomAD downloads
        # expand(
        #     [
        #         "resources/gnomad/{gnomad_type}/gnomad.{gnomad_type}.v4.1.sites.chr{chr}.vcf.bgz",
        #     ],
        #     gnomad_type=GNOMAD_TYPES,
        #     chr=CHROMOSOMES_MAIN,
        # ),
        # "resources/gnomad/genomes/gnomad.genomes.v3.1.sites.chrM.vcf.bgz",
        expand(
            [
                "resources/gnomad/{gnomad_type}/gnomad.{gnomad_type}.v4.1.sites.{chr}.renamed.vcf.gz",
                "resources/gnomad/{gnomad_type}/gnomad.{gnomad_type}.v4.1.sites.{chr}.renamed.vcf.gz.csi",
            ],
            gnomad_type=GNOMAD_TYPES,
            chr=CHROMOSOMES_MAIN,
        ),
        "resources/gnomad/genomes/gnomad.genomes.v3.1.sites.MT.renamed.vcf.gz",
        # gnomAD annotated VCFs
        expand(
            "results/calls/{sample}_annotated.vcf.gz",
            sample=get_active_samples(),
        ),
