# ============================================
# Estimate-MSI-Workflow - Main Entry Point
# ============================================

configfile: "config/config.yaml"

include: "rules/common.smk"
include: "rules/ref.smk"
include: "rules/microsatellites.smk"
include: "rules/reads.smk"
include: "rules/alignment.smk"
include: "rules/variant_calling.smk"
include: "rules/msi.smk"


rule all:
    input:
        "resources/genome.fasta",
        "resources/genome.gtf",
        "resources/genome.fasta.fai",
        multiext("resources/genome.fasta", ".amb", ".ann", ".bwt", ".pac", ".sa")
